-- MySQL Script generated by MySQL Workbench
-- 12/18/15 10:40:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Onboard_Test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Onboard_Test` ;

-- -----------------------------------------------------
-- Schema Onboard_Test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Onboard_Test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Onboard_Test` ;

-- -----------------------------------------------------
-- Table `Onboard_Test`.`Companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onboard_Test`.`Companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_name` VARCHAR(50) NOT NULL COMMENT '',
  `company_address` VARCHAR(45) NOT NULL COMMENT '',
  `company_phone_number` INT NOT NULL COMMENT '',
  PRIMARY KEY (`company_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onboard_Test`.`Meetings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onboard_Test`.`Meetings` (
  `meeting_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `meeting_name` VARCHAR(45) NOT NULL COMMENT '',
  `meeting_time` INT NOT NULL COMMENT '',
  `meeting_date` INT NOT NULL COMMENT '',
  PRIMARY KEY (`meeting_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onboard_Test`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onboard_Test`.`Employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `job_title` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`employee_id`)  COMMENT '',
  INDEX `fk_Employee_Companies_idx` (`company_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Employee_Companies`
    FOREIGN KEY (`company_id`)
    REFERENCES `Onboard_Test`.`Companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onboard_Test`.`Meeting_Attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onboard_Test`.`Meeting_Attendance` (
  `attendance_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  `meeting_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`attendance_id`)  COMMENT '',
  INDEX `fk_Meeting_Attendance_Employee1_idx` (`employee_id` ASC)  COMMENT '',
  INDEX `fk_Meeting_Attendance_Meetings1_idx` (`meeting_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Meeting_Attendance_Employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Onboard_Test`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Meeting_Attendance_Meetings1`
    FOREIGN KEY (`meeting_id`)
    REFERENCES `Onboard_Test`.`Meetings` (`meeting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
